config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'tasks', to: 'tasks#index'
  post 'tasks', to: 'tasks#create'
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new', as: :new_task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  get 'tasks/:id',      to: 'tasks#show', as: :task

  patch 'tasks/:id',    to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'

  patch 'tasks/:id/mark_as_done', to: 'tasks#mark_as_done', as: :mark_as_done
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :mark_as_done]

  def index
    @tasks = Task.all
  end

  def show
    build_status_message
  end

  def new
    @task = Task.new
  end

  def create
    # 1. Construire un object task à partir de params[:task]
    task = Task.new(task_params)
    # 2. Sauver l'objet en DB
    task.save
    # 3. Redirige vers la liste des restos
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def build_status_message
    # @status = @task[:completed]
    if @task[:completed] == true
      @status = "Task completed!"
    else
      @status = "Task not completed"
      # link_to 'Mark it as done?', method: :mark_as_done
    end
  end

  def mark_as_done
    @task.update(completed: true)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Wesh</h1>
<%= link_to 'Restaurants', '/tasks' %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task: <%= @task.title %></h1>

<%= render 'form' %>

<%= link_to 'Go back to all tasks', tasks_path %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= link_to task.title, task_path(task) %> <%= link_to '[X]', task_path(task), method: :delete, data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>


<%= link_to 'Add new task', new_task_path %>

app/views/tasks/new.html.erb
<h1>Add a new task</h1>

<%= render 'form' %>

<%= link_to 'Go back to all tasks', tasks_path %>

app/views/tasks/show.html.erb
<h1>Task page</h1>

<ul>
  <li><strong>Name:</strong> <%= @task[:title] %></li>
  <li><strong>Address:</strong> <%= @task[:details] %></li>
</ul>


<%= @status %>
<%=
if @task[:completed] == true
  "Task completed!"
else
  "Task not completed"
  link_to 'Mark as completed', mark_as_done_path(@task), method: :patch
end
 %>
 <br>


<br>
<br>
<%= link_to 'Edit', edit_task_path %>
<br>
<%= link_to 'Back to list', tasks_path %>